require("core.plugins")
require("core.mappings")
require("core.colors")
require("core.settings")

require("plugins.lsp")
require("plugins.neotree")
require("plugins.onedark")
require("plugins.kanagawa")
require("plugins.treesitter")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.bufferline")
require("plugins.comments")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.tabnine")
