-- basic
require("core.plugins")
require("core.mappings")
require("core.themes")
require("core.configs")
require("core.autocmds")

-- plugins
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.gitsigns")
require("plugins.kanagawa")
require("plugins.vscode_theme")
require("plugins.comments")
require("plugins.toggleterm")
require("plugins.withkey")
require("plugins.autotag")
require("plugins.dap")
